#!/bin/bash -e

if [ "$1" = "twoa" ]
then
	echo 'Calculating...'
	echo '' | gap -q twoa.gap

	echo 'Zipping...'
	zip -q -j results results/*
elif [ "$1" = "bench" ]
then
	echo 'Benchmarking...'
	echo '' | gap -q benchmark-twoa.gap
else
    echo 'Usage: ./run [twoa|bench]'
fi

exit 0
